/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as ApiPublicDataRetentionRouteImport } from './routes/api/public/data-retention'
import { Route as ApiPublicMetaSocialWebhookRouteImport } from './routes/api/public/meta-social-webhook'
import { Route as ApiPublicResendWebhookRouteImport } from './routes/api/public/resend-webhook'
import { Route as ApiPublicRunScheduledRouteImport } from './routes/api/public/run-scheduled'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ReleaseClientSlugReleaseSlugRouteImport } from './routes/release.$clientSlug.$releaseSlug'
import { Route as ApiPublicRCodeRouteImport } from './routes/api/public/r.$code'
import { Route as ApiPublicReleaseImageReleaseIdRouteImport } from './routes/api/public/release-image.$releaseId'
import { Route as ApiPublicUnsubscribeTokenRouteImport } from './routes/api/public/unsubscribe.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDataRetentionRoute = ApiPublicDataRetentionRouteImport.update({
  id: '/api/public/data-retention',
  path: '/api/public/data-retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaSocialWebhookRoute =
  ApiPublicMetaSocialWebhookRouteImport.update({
    id: '/api/public/meta-social-webhook',
    path: '/api/public/meta-social-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResendWebhookRoute = ApiPublicResendWebhookRouteImport.update({
  id: '/api/public/resend-webhook',
  path: '/api/public/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunScheduledRoute = ApiPublicRunScheduledRouteImport.update({
  id: '/api/public/run-scheduled',
  path: '/api/public/run-scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReleaseClientSlugReleaseSlugRoute =
  ReleaseClientSlugReleaseSlugRouteImport.update({
    id: '/release/$clientSlug/$releaseSlug',
    path: '/release/$clientSlug/$releaseSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRCodeRoute = ApiPublicRCodeRouteImport.update({
  id: '/api/public/r/$code',
  path: '/api/public/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReleaseImageReleaseIdRoute =
  ApiPublicReleaseImageReleaseIdRouteImport.update({
    id: '/api/public/release-image/$releaseId',
    path: '/api/public/release-image/$releaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUnsubscribeTokenRoute =
  ApiPublicUnsubscribeTokenRouteImport.update({
    id: '/api/public/unsubscribe/$token',
    path: '/api/public/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/api/public/data-retention': typeof ApiPublicDataRetentionRoute
  '/api/public/meta-social-webhook': typeof ApiPublicMetaSocialWebhookRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/run-scheduled': typeof ApiPublicRunScheduledRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/release/$clientSlug/$releaseSlug': typeof ReleaseClientSlugReleaseSlugRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/api/public/release-image/$releaseId': typeof ApiPublicReleaseImageReleaseIdRoute
  '/api/public/unsubscribe/$token': typeof ApiPublicUnsubscribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/api/public/data-retention': typeof ApiPublicDataRetentionRoute
  '/api/public/meta-social-webhook': typeof ApiPublicMetaSocialWebhookRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/run-scheduled': typeof ApiPublicRunScheduledRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/release/$clientSlug/$releaseSlug': typeof ReleaseClientSlugReleaseSlugRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/api/public/release-image/$releaseId': typeof ApiPublicReleaseImageReleaseIdRoute
  '/api/public/unsubscribe/$token': typeof ApiPublicUnsubscribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/api/public/data-retention': typeof ApiPublicDataRetentionRoute
  '/api/public/meta-social-webhook': typeof ApiPublicMetaSocialWebhookRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/run-scheduled': typeof ApiPublicRunScheduledRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/release/$clientSlug/$releaseSlug': typeof ReleaseClientSlugReleaseSlugRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/api/public/release-image/$releaseId': typeof ApiPublicReleaseImageReleaseIdRoute
  '/api/public/unsubscribe/$token': typeof ApiPublicUnsubscribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/api/public/data-retention'
    | '/api/public/meta-social-webhook'
    | '/api/public/resend-webhook'
    | '/api/public/run-scheduled'
    | '/api/public/whatsapp-webhook'
    | '/release/$clientSlug/$releaseSlug'
    | '/api/public/r/$code'
    | '/api/public/release-image/$releaseId'
    | '/api/public/unsubscribe/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel'
    | '/api/public/data-retention'
    | '/api/public/meta-social-webhook'
    | '/api/public/resend-webhook'
    | '/api/public/run-scheduled'
    | '/api/public/whatsapp-webhook'
    | '/release/$clientSlug/$releaseSlug'
    | '/api/public/r/$code'
    | '/api/public/release-image/$releaseId'
    | '/api/public/unsubscribe/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/api/public/data-retention'
    | '/api/public/meta-social-webhook'
    | '/api/public/resend-webhook'
    | '/api/public/run-scheduled'
    | '/api/public/whatsapp-webhook'
    | '/release/$clientSlug/$releaseSlug'
    | '/api/public/r/$code'
    | '/api/public/release-image/$releaseId'
    | '/api/public/unsubscribe/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDataRetentionRoute: typeof ApiPublicDataRetentionRoute
  ApiPublicMetaSocialWebhookRoute: typeof ApiPublicMetaSocialWebhookRoute
  ApiPublicResendWebhookRoute: typeof ApiPublicResendWebhookRoute
  ApiPublicRunScheduledRoute: typeof ApiPublicRunScheduledRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ReleaseClientSlugReleaseSlugRoute: typeof ReleaseClientSlugReleaseSlugRoute
  ApiPublicRCodeRoute: typeof ApiPublicRCodeRoute
  ApiPublicReleaseImageReleaseIdRoute: typeof ApiPublicReleaseImageReleaseIdRoute
  ApiPublicUnsubscribeTokenRoute: typeof ApiPublicUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/data-retention': {
      id: '/api/public/data-retention'
      path: '/api/public/data-retention'
      fullPath: '/api/public/data-retention'
      preLoaderRoute: typeof ApiPublicDataRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-social-webhook': {
      id: '/api/public/meta-social-webhook'
      path: '/api/public/meta-social-webhook'
      fullPath: '/api/public/meta-social-webhook'
      preLoaderRoute: typeof ApiPublicMetaSocialWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-webhook': {
      id: '/api/public/resend-webhook'
      path: '/api/public/resend-webhook'
      fullPath: '/api/public/resend-webhook'
      preLoaderRoute: typeof ApiPublicResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-scheduled': {
      id: '/api/public/run-scheduled'
      path: '/api/public/run-scheduled'
      fullPath: '/api/public/run-scheduled'
      preLoaderRoute: typeof ApiPublicRunScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release/$clientSlug/$releaseSlug': {
      id: '/release/$clientSlug/$releaseSlug'
      path: '/release/$clientSlug/$releaseSlug'
      fullPath: '/release/$clientSlug/$releaseSlug'
      preLoaderRoute: typeof ReleaseClientSlugReleaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/$code': {
      id: '/api/public/r/$code'
      path: '/api/public/r/$code'
      fullPath: '/api/public/r/$code'
      preLoaderRoute: typeof ApiPublicRCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/release-image/$releaseId': {
      id: '/api/public/release-image/$releaseId'
      path: '/api/public/release-image/$releaseId'
      fullPath: '/api/public/release-image/$releaseId'
      preLoaderRoute: typeof ApiPublicReleaseImageReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe/$token': {
      id: '/api/public/unsubscribe/$token'
      path: '/api/public/unsubscribe/$token'
      fullPath: '/api/public/unsubscribe/$token'
      preLoaderRoute: typeof ApiPublicUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDataRetentionRoute: ApiPublicDataRetentionRoute,
  ApiPublicMetaSocialWebhookRoute: ApiPublicMetaSocialWebhookRoute,
  ApiPublicResendWebhookRoute: ApiPublicResendWebhookRoute,
  ApiPublicRunScheduledRoute: ApiPublicRunScheduledRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ReleaseClientSlugReleaseSlugRoute: ReleaseClientSlugReleaseSlugRoute,
  ApiPublicRCodeRoute: ApiPublicRCodeRoute,
  ApiPublicReleaseImageReleaseIdRoute: ApiPublicReleaseImageReleaseIdRoute,
  ApiPublicUnsubscribeTokenRoute: ApiPublicUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
